// trading_platform/frontend/src/components/OrderbookTable.svelte
<script lang="ts">
  export let dom: { ts: number; bids: [number, number][]; asks: [number, number][] } | null = null
  export let depth: number = 20

  $: bids = dom?.bids?.slice(0, depth) || []
  $: asks = dom?.asks?.slice(0, depth) || []

  // Calculate cumulative totals
  $: bidsWithTotal = bids.map((bid, i) => {
    const total = bids.slice(0, i + 1).reduce((sum, [_, size]) => sum + size, 0)
    return { price: bid[0], size: bid[1], total }
  })

  $: asksWithTotal = asks.map((ask, i) => {
    const total = asks.slice(0, i + 1).reduce((sum, [_, size]) => sum + size, 0)
    return { price: ask[0], size: ask[1], total }
  })

  $: maxTotal = Math.max(
    ...bidsWithTotal.map(b => b.total),
    ...asksWithTotal.map(a => a.total),
    1
  )

  function formatPrice(price: number): string {
    return price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  }

  function formatSize(size: number): string {
    if (size >= 1000) return size.toFixed(2)
    if (size >= 1) return size.toFixed(4)
    return size.toFixed(6)
  }
</script>

<div class="orderbook">
  <div class="orderbook-header">
    <div class="header-col">Price</div>
    <div class="header-col">Size</div>
    <div class="header-col">Total</div>
  </div>
  <div class="orderbook-body">
    <!-- Asks (top, red) -->
    <div class="asks">
      {#each asksWithTotal as ask}
        <div class="row ask" style="--width: {(ask.total / maxTotal) * 100}%">
          <div class="col price">{formatPrice(ask.price)}</div>
          <div class="col size">{formatSize(ask.size)}</div>
          <div class="col total">{formatSize(ask.total)}</div>
        </div>
      {/each}
    </div>
    <!-- Spread -->
    {#if bids.length > 0 && asks.length > 0}
      <div class="spread">
        <div class="spread-label">Spread</div>
        <div class="spread-value">
          {formatPrice(asks[0][0] - bids[0][0])} ({(asks[0][0] - bids[0][0]) / bids[0][0] * 10000} bps)
        </div>
      </div>
    {/if}
    <!-- Bids (bottom, green) -->
    <div class="bids">
      {#each bidsWithTotal as bid}
        <div class="row bid" style="--width: {(bid.total / maxTotal) * 100}%">
          <div class="col price">{formatPrice(bid.price)}</div>
          <div class="col size">{formatSize(bid.size)}</div>
          <div class="col total">{formatSize(bid.total)}</div>
        </div>
      {/each}
    </div>
  </div>
</div>

<style>
  .orderbook {
    display: flex;
    flex-direction: column;
    font-family: 'Courier New', monospace;
    font-size: 12px;
    color: var(--text, #e0e0e0);
    background: var(--bg-panel, #0a0a0a);
  }

  .orderbook-header {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    padding: 6px 8px;
    border-bottom: 1px solid var(--border, #333);
    font-weight: 600;
    font-size: 11px;
    color: var(--text-muted, #888);
  }

  .orderbook-body {
    display: flex;
    flex-direction: column;
    max-height: 600px;
    overflow-y: auto;
  }

  .asks {
    display: flex;
    flex-direction: column-reverse;
  }

  .bids {
    display: flex;
    flex-direction: column;
  }

  .row {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    padding: 2px 8px;
    position: relative;
    cursor: pointer;
    transition: background 0.1s;
  }

  .row:hover {
    background: rgba(255, 255, 255, 0.05);
  }

  .row.ask {
    color: var(--sell, #ef4444);
  }

  .row.ask::before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    width: var(--width);
    background: rgba(239, 68, 68, 0.1);
    z-index: -1;
  }

  .row.bid {
    color: var(--buy, #10b981);
  }

  .row.bid::before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    width: var(--width);
    background: rgba(16, 185, 129, 0.1);
    z-index: -1;
  }

  .col {
    text-align: right;
    font-variant-numeric: tabular-nums;
  }

  .col.price {
    text-align: left;
  }

  .spread {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px;
    border-top: 1px solid var(--border, #333);
    border-bottom: 1px solid var(--border, #333);
    background: var(--bg, #050505);
    font-weight: 600;
  }

  .spread-label {
    font-size: 11px;
    color: var(--text-muted, #888);
  }

  .spread-value {
    font-size: 12px;
    color: var(--text, #e0e0e0);
  }
</style>

// trading_platform/frontend/src/components/OrderbookTable.tsx
import React, { useMemo } from 'react'
import { formatPrice, formatSize } from '../lib/format'

export interface DOMData {
  ts: number
  bids: [number, number][]
  asks: [number, number][]
}

interface OrderbookTableProps {
  dom: DOMData | null
  depth?: number
}

interface OrderbookRow {
  price: number
  size: number
  total: number
}

export const OrderbookTable: React.FC<OrderbookTableProps> = ({ dom, depth = 20 }) => {
  const { bids, asks, maxTotal } = useMemo(() => {
    if (!dom) {
      return { bids: [], asks: [], maxTotal: 1 }
    }

    const bidsList = dom.bids.slice(0, depth)
    const asksList = dom.asks.slice(0, depth)

    const bidsWithTotal: OrderbookRow[] = bidsList.map((bid, i) => {
      const total = bidsList.slice(0, i + 1).reduce((sum, [, size]) => sum + size, 0)
      return { price: bid[0], size: bid[1], total }
    })

    const asksWithTotal: OrderbookRow[] = asksList.map((ask, i) => {
      const total = asksList.slice(0, i + 1).reduce((sum, [, size]) => sum + size, 0)
      return { price: ask[0], size: ask[1], total }
    })

    const maxTotal = Math.max(
      ...bidsWithTotal.map(b => b.total),
      ...asksWithTotal.map(a => a.total),
      1
    )

    return { bids: bidsWithTotal, asks: asksWithTotal, maxTotal }
  }, [dom, depth])

  const spread = useMemo(() => {
    if (bids.length === 0 || asks.length === 0) return null
    const spreadValue = asks[0].price - bids[0].price
    const spreadBps = (spreadValue / bids[0].price) * 10000
    return { value: spreadValue, bps: spreadBps }
  }, [bids, asks])

  return (
    <div className="orderbook">
      <div className="orderbook-header">
        <div className="header-col">Price</div>
        <div className="header-col">Size</div>
        <div className="header-col">Total</div>
      </div>
      <div className="orderbook-body">
        {/* Asks (top, red) */}
        <div className="asks">
          {asks.slice().reverse().map((ask, idx) => (
            <div
              key={`ask-${ask.price}-${idx}`}
              className="row ask"
              style={{ '--width': `${(ask.total / maxTotal) * 100}%` } as React.CSSProperties}
            >
              <div className="col price">{formatPrice(ask.price)}</div>
              <div className="col size">{formatSize(ask.size)}</div>
              <div className="col total">{formatSize(ask.total)}</div>
            </div>
          ))}
        </div>

        {/* Spread */}
        {spread && (
          <div className="spread">
            <div className="spread-label">Spread</div>
            <div className="spread-value">
              {formatPrice(spread.value)} ({spread.bps.toFixed(2)} bps)
            </div>
          </div>
        )}

        {/* Bids (bottom, green) */}
        <div className="bids">
          {bids.map((bid, idx) => (
            <div
              key={`bid-${bid.price}-${idx}`}
              className="row bid"
              style={{ '--width': `${(bid.total / maxTotal) * 100}%` } as React.CSSProperties}
            >
              <div className="col price">{formatPrice(bid.price)}</div>
              <div className="col size">{formatSize(bid.size)}</div>
              <div className="col total">{formatSize(bid.total)}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
